##build docker pserver
#bash setup_image.sh latest
#or
#bash setup_container.sh latest /path/to/config.json

FROM nvcr.io/nvidia/l4t-base:r32.5.0

ARG PSERVER_VERSION=latest

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    curl \
    git \
    nano \
    pkg-config \
    v4l-utils \
    usbutils
RUN curl -L git.io/nodebrew | perl - setup
RUN echo "export PATH=$HOME/.nodebrew/current/bin:\$PATH" >> $HOME/.bashrc
ENV HOME /root
ENV PATH $HOME/.nodebrew/current/bin:$PATH
RUN sed -i -z "s/} elsif (\$machine =~ m\/aarch64\/) {\n        \$arch = 'armv7l';/} elsif (\$machine =~ m\/aarch64\/) {\n        \$arch = 'arm64'/g" $HOME/.nodebrew/nodebrew
RUN nodebrew install v14.17.1 && \
    nodebrew use v14.17.1
RUN npm config set unsafe-perm true && \
    npm -g install node-pserver@${PSERVER_VERSION}
RUN cp /root/.nodebrew/current/lib/node_modules/node-pserver/node_modules/node-pstcore/build/Release/libopencv_calib3d.so.4.1 /usr/lib/aarch64-linux-gnu/libopencv_calib3d.so.4.1
RUN cp /root/.nodebrew/current/lib/node_modules/node-pserver/node_modules/node-pstcore/build/Release/libopencv_core.so.4.1 /usr/lib/aarch64-linux-gnu/libopencv_core.so.4.1
RUN cp /root/.nodebrew/current/lib/node_modules/node-pserver/node_modules/node-pstcore/build/Release/libopencv_imgproc.so.4.1 /usr/lib/aarch64-linux-gnu/libopencv_imgproc.so.4.1
RUN cp /root/.nodebrew/current/lib/node_modules/node-pserver/node_modules/node-pstcore/build/Release/libopencv_features2d.so.4.1 /usr/lib/aarch64-linux-gnu/libopencv_features2d.so.4.1
RUN cp /root/.nodebrew/current/lib/node_modules/node-pserver/node_modules/node-pstcore/build/Release/libopencv_flann.so.4.1 /usr/lib/aarch64-linux-gnu/libopencv_flann.so.4.1
RUN cp /root/.nodebrew/current/lib/node_modules/node-pserver/node_modules/node-pstcore/build/Release/libtbb.so.2 /usr/lib/aarch64-linux-gnu/libtbb.so.2

COPY etc/udev/99-hqcam.rules /etc/udev/rules.d/99-hqcam.rules
COPY etc/pserver/mono-config.json /root/mono-config.json
COPY etc/pserver/stereo-config.json /root/stereo-config.json
COPY etc/pserver/hq-mono-config.json /root/hq-mono-config.json
COPY etc/pserver/hq-stereo-config.json /root/hq-stereo-config.json
COPY etc/pserver/lens_params0.json /root/lens_params0.json
COPY etc/pserver/lens_params1.json /root/lens_params1.json
COPY www/config.json /root/.nodebrew/current/lib/node_modules/node-pserver/www/config.json

EXPOSE 9001
ENTRYPOINT ["pserver"]
